### ISSUE TITLE
Check is not complete: Status: unknown, Run ID: unknown

### ISSUE THREAD

**Issue by zomars** [blend/require-conditional-status-checks#14]
Hey @dvdliao any ideas on why this might be happening?

<img width="628" alt="image" src="https://user-images.githubusercontent.com/3504472/178375408-ffa4ab83-d7c9-4bf5-813d-e83ca0005121.png">

I've made sure I've named all [our tasks differently](https://github.com/calcom/cal.com/tree/main/.github/workflows).

Also I thought since some tasks we're running on `pull_request_target` I've thought that would have something to do (as detailed on #12) and changed them to `pull_request` but no luck still.

**Comment by dvdliao** [comment]
hey @zomars I'm not exactly sure but just by eyeballing i think its to do with your `matrix` usage, i do see that right now you are still spawning only 1 job, so maybe try removing matrix?

**Comment by zomars** [comment]
> hey @zomars I'm not exactly sure but just by eyeballing i think its to do with your `matrix` usage, i do see that right now you are still spawning only 1 job, so maybe try removing matrix?

Thanks for the pointer. Will try and report back

**Comment by zomars** [comment]
Ok, these are my findings. Removing the matrix worked only for the `lint` task:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/3504472/178381499-01d09585-7369-49a3-b270-bfebe55c7316.png">

So I've dug further and found out that the `lint` task was the only without a set `name` in the job. So [removing the `name` from the other tasks jobs](https://github.com/calcom/cal.com/commit/012af52f1b6c3023d97ba42485515c2eb4c9d39f) did the trick:

<img width="672" alt="image" src="https://user-images.githubusercontent.com/3504472/178382758-b039798c-bf6f-4a6b-83b7-4f72b486e7d7.png">


Thanks again @dvdliao 🙏🏽

**Comment by dvdliao** [comment]
awesome! you can also use the job `name` in the require checks yaml so you don't have to remove it.
