### ISSUE TITLE
Why is there no source code?

### ISSUE THREAD

**Issue by ashishb** [blend/require-conditional-status-checks#16]
How trustworthy are these binaries?
Where's the source code that was used for building this?

**Comment by dhermes** [comment]
@ashishb Thanks for asking. If you look at https://github.com/blend/require-conditional-status-checks/branches you'll see `release` and `development` branches.

The source code (and build files, etc.) lives in the `development` branch and the `release` branch is kept minimal to ensure that using this repo as a GitHub Action is VERY fast.

**Comment by ashishb** [comment]
Thanks @dhermes for the clarification.
